/** @type {import('ts-jest').JestConfigWithTsJest} **/
module.exports = {
  testEnvironment: "node",
  roots: ["<rootDir>/backend", "<rootDir>/src", "<rootDir>/models", "<rootDir>/tests"],
  testMatch: ["**/*.test.ts", "**/*.test.tsx", "**/__tests__/**/*.ts"],
  transform: {
    "^.+\\.tsx?$": ["ts-jest", { tsconfig: { jsx: "react-jsx" } }],
  },
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@b/(.*)$": "<rootDir>/backend/$1",
    "^@db/(.*)$": "<rootDir>/models/$1",
    "\\.(css|less|scss|sass)$": "<rootDir>/tests/__mocks__/styleMock.js",
    "\\.(jpg|jpeg|png|gif|webp|svg)$": "<rootDir>/tests/__mocks__/fileMock.js",
  },
  projects: [
    {
      displayName: "api-unit",
      testMatch: ["<rootDir>/tests/unit/api/**/*.test.ts"],
      testEnvironment: "node",
      transform: { "^.+\\.tsx?$": ["ts-jest", { tsconfig: { jsx: "react-jsx" } }] },
      moduleNameMapper: {
        "^@/(.*)$": "<rootDir>/src/$1",
        "^@b/(.*)$": "<rootDir>/backend/$1",
        "^@db/(.*)$": "<rootDir>/models/$1",
        "\\.(css|less|scss|sass)$": "<rootDir>/tests/__mocks__/styleMock.js",
        "\\.(jpg|jpeg|png|gif|webp|svg)$": "<rootDir>/tests/__mocks__/fileMock.js",
      },
      setupFilesAfterEnv: ["<rootDir>/tests/setup.ts", "<rootDir>/tests/unit/api/setup-api.ts"],
      clearMocks: true,
      restoreMocks: false,
    },
    {
      displayName: "default",
      testMatch: ["<rootDir>/tests/**/*.test.ts", "<rootDir>/tests/**/*.test.tsx", "<rootDir>/backend/**/*.test.ts"],
      testPathIgnorePatterns: ["/node_modules/", "/.next/", "/dist/", "<rootDir>/tests/unit/api/"],
      testEnvironment: "node",
      transform: { "^.+\\.tsx?$": ["ts-jest", { tsconfig: { jsx: "react-jsx" } }] },
      moduleNameMapper: {
        "^@/(.*)$": "<rootDir>/src/$1",
        "^@b/(.*)$": "<rootDir>/backend/$1",
        "^@db/(.*)$": "<rootDir>/models/$1",
        "\\.(css|less|scss|sass)$": "<rootDir>/tests/__mocks__/styleMock.js",
        "\\.(jpg|jpeg|png|gif|webp|svg)$": "<rootDir>/tests/__mocks__/fileMock.js",
      },
      setupFilesAfterEnv: ["<rootDir>/tests/setup.ts"],
      clearMocks: true,
      restoreMocks: true,
    },
  ],
  setupFilesAfterEnv: ["<rootDir>/tests/setup.ts"],
  testPathIgnorePatterns: ["/node_modules/", "/.next/", "/dist/"],
  collectCoverageFrom: [
    "src/utils/**/*.ts",
    "backend/utils/**/*.ts",
    "backend/api/**/*.ts",
    "models/**/*.ts",
    "!**/*.d.ts",
    "!**/node_modules/**",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "json-summary"],
  clearMocks: true,
  restoreMocks: true,
};
